name: Update Docker Hub Images

on:
  schedule:
  - cron: "14 19 * * *"
  push:

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker hub
      run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push images
      run: ./build-all.sh
