name: Docker Image CI

on:
  schedule:
  - cron: "0 16 * * *"
  push:

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Update Dockerfiles
      run: ./update.sh
    - name: Build and push Images
      run: ./build.sh
